### ISSUE TITLE
Support for "raise X from Y" exception nesting

### ISSUE THREAD

**Issue by Forst** [albertz/py_better_exchook#1]
Been enjoying using this exception hook so far, produces way more useful tracebacks, thanks!

However one feature I find missing is support for [exception nesting](https://docs.python.org/3/reference/simple_stmts.html#raise) in Python 3. Consider the following code:

```python
class OuterException(Exception):
    def __init__(self):
        super().__init__('Outer exception message')

class InnerException(Exception):
    def __init__(self):
        super().__init__('Inner exception message')

try:
    raise InnerException()
except Exception as e:
    raise OuterException() from e
```

The standard traceback then looks like this:

```
Traceback (most recent call last):
  File "path/to/example.py", line 22, in <module>
    raise InnerException()
__main__.InnerException: Inner exception message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "path/to/example.py", line 24, in <module>
    raise OuterException() from e
__main__.OuterException: Outer exception message
```

`better_exchook` outputs this however:

```
EXCEPTION
Traceback (most recent call last):
  File "path/to/example.py", line 22, in <module>
    line: raise OuterException() from e
    locals:
      OuterException = <local> <class '__main__.OuterException'>
      e = <not found>
OuterException: Outer exception message
```

The information about the inner exception is not displayed. Would be great to be able to see it too.

**Comment by albertz** [comment]
I just implemented it. Can you try?

**Comment by Forst** [comment]
Works great here! Thank you so much for an incredibly quick implementation :heart:
